// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.12.4
// source: proto/control.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WeightControl_UpdateWeight_FullMethodName  = "/control.WeightControl/UpdateWeight"
	WeightControl_AddBackend_FullMethodName    = "/control.WeightControl/AddBackend"
	WeightControl_DeleteBackend_FullMethodName = "/control.WeightControl/DeleteBackend"
)

// WeightControlClient is the client API for WeightControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WeightControlClient interface {
	UpdateWeight(ctx context.Context, in *WeightRequest, opts ...grpc.CallOption) (*Empty, error)
	AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteBackend(ctx context.Context, in *DeleteBackendRequest, opts ...grpc.CallOption) (*Empty, error)
}

type weightControlClient struct {
	cc grpc.ClientConnInterface
}

func NewWeightControlClient(cc grpc.ClientConnInterface) WeightControlClient {
	return &weightControlClient{cc}
}

func (c *weightControlClient) UpdateWeight(ctx context.Context, in *WeightRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WeightControl_UpdateWeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightControlClient) AddBackend(ctx context.Context, in *AddBackendRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WeightControl_AddBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightControlClient) DeleteBackend(ctx context.Context, in *DeleteBackendRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, WeightControl_DeleteBackend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightControlServer is the server API for WeightControl service.
// All implementations must embed UnimplementedWeightControlServer
// for forward compatibility
type WeightControlServer interface {
	UpdateWeight(context.Context, *WeightRequest) (*Empty, error)
	AddBackend(context.Context, *AddBackendRequest) (*Empty, error)
	DeleteBackend(context.Context, *DeleteBackendRequest) (*Empty, error)
	mustEmbedUnimplementedWeightControlServer()
}

// UnimplementedWeightControlServer must be embedded to have forward compatible implementations.
type UnimplementedWeightControlServer struct {
}

func (UnimplementedWeightControlServer) UpdateWeight(context.Context, *WeightRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWeight not implemented")
}
func (UnimplementedWeightControlServer) AddBackend(context.Context, *AddBackendRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBackend not implemented")
}
func (UnimplementedWeightControlServer) DeleteBackend(context.Context, *DeleteBackendRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBackend not implemented")
}
func (UnimplementedWeightControlServer) mustEmbedUnimplementedWeightControlServer() {}

// UnsafeWeightControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeightControlServer will
// result in compilation errors.
type UnsafeWeightControlServer interface {
	mustEmbedUnimplementedWeightControlServer()
}

func RegisterWeightControlServer(s grpc.ServiceRegistrar, srv WeightControlServer) {
	s.RegisterService(&WeightControl_ServiceDesc, srv)
}

func _WeightControl_UpdateWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightControlServer).UpdateWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeightControl_UpdateWeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightControlServer).UpdateWeight(ctx, req.(*WeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeightControl_AddBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightControlServer).AddBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeightControl_AddBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightControlServer).AddBackend(ctx, req.(*AddBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeightControl_DeleteBackend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBackendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightControlServer).DeleteBackend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeightControl_DeleteBackend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightControlServer).DeleteBackend(ctx, req.(*DeleteBackendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeightControl_ServiceDesc is the grpc.ServiceDesc for WeightControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeightControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.WeightControl",
	HandlerType: (*WeightControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateWeight",
			Handler:    _WeightControl_UpdateWeight_Handler,
		},
		{
			MethodName: "AddBackend",
			Handler:    _WeightControl_AddBackend_Handler,
		},
		{
			MethodName: "DeleteBackend",
			Handler:    _WeightControl_DeleteBackend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control.proto",
}
