// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/control.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightRequest) Reset() {
	*x = WeightRequest{}
	mi := &file_proto_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightRequest) ProtoMessage() {}

func (x *WeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightRequest.ProtoReflect.Descriptor instead.
func (*WeightRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{0}
}

func (x *WeightRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *WeightRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *WeightRequest) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type AddBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBackendRequest) Reset() {
	*x = AddBackendRequest{}
	mi := &file_proto_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBackendRequest) ProtoMessage() {}

func (x *AddBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBackendRequest.ProtoReflect.Descriptor instead.
func (*AddBackendRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{1}
}

func (x *AddBackendRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddBackendRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AddBackendRequest) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type DeleteBackendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBackendRequest) Reset() {
	*x = DeleteBackendRequest{}
	mi := &file_proto_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBackendRequest) ProtoMessage() {}

func (x *DeleteBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBackendRequest.ProtoReflect.Descriptor instead.
func (*DeleteBackendRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteBackendRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *DeleteBackendRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRequest) Reset() {
	*x = ServiceRequest{}
	mi := &file_proto_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRequest) ProtoMessage() {}

func (x *ServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRequest.ProtoReflect.Descriptor instead.
func (*ServiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ServiceRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_control_proto_rawDescGZIP(), []int{4}
}

var File_proto_control_proto protoreflect.FileDescriptor

const file_proto_control_proto_rawDesc = "" +
	"\n" +
	"\x13proto/control.proto\x12\acontrol\"K\n" +
	"\rWeightRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\"O\n" +
	"\x11AddBackendRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\":\n" +
	"\x14DeleteBackendRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"4\n" +
	"\x0eServiceRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"\a\n" +
	"\x05Empty2\xb2\x02\n" +
	"\rWeightControl\x126\n" +
	"\fUpdateWeight\x12\x16.control.WeightRequest\x1a\x0e.control.Empty\x128\n" +
	"\n" +
	"AddBackend\x12\x1a.control.AddBackendRequest\x1a\x0e.control.Empty\x12>\n" +
	"\rDeleteBackend\x12\x1d.control.DeleteBackendRequest\x1a\x0e.control.Empty\x125\n" +
	"\n" +
	"AddService\x12\x17.control.ServiceRequest\x1a\x0e.control.Empty\x128\n" +
	"\rDeleteService\x12\x17.control.ServiceRequest\x1a\x0e.control.EmptyB\n" +
	"Z\blb/protob\x06proto3"

var (
	file_proto_control_proto_rawDescOnce sync.Once
	file_proto_control_proto_rawDescData []byte
)

func file_proto_control_proto_rawDescGZIP() []byte {
	file_proto_control_proto_rawDescOnce.Do(func() {
		file_proto_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)))
	})
	return file_proto_control_proto_rawDescData
}

var file_proto_control_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_control_proto_goTypes = []any{
	(*WeightRequest)(nil),        // 0: control.WeightRequest
	(*AddBackendRequest)(nil),    // 1: control.AddBackendRequest
	(*DeleteBackendRequest)(nil), // 2: control.DeleteBackendRequest
	(*ServiceRequest)(nil),       // 3: control.ServiceRequest
	(*Empty)(nil),                // 4: control.Empty
}
var file_proto_control_proto_depIdxs = []int32{
	0, // 0: control.WeightControl.UpdateWeight:input_type -> control.WeightRequest
	1, // 1: control.WeightControl.AddBackend:input_type -> control.AddBackendRequest
	2, // 2: control.WeightControl.DeleteBackend:input_type -> control.DeleteBackendRequest
	3, // 3: control.WeightControl.AddService:input_type -> control.ServiceRequest
	3, // 4: control.WeightControl.DeleteService:input_type -> control.ServiceRequest
	4, // 5: control.WeightControl.UpdateWeight:output_type -> control.Empty
	4, // 6: control.WeightControl.AddBackend:output_type -> control.Empty
	4, // 7: control.WeightControl.DeleteBackend:output_type -> control.Empty
	4, // 8: control.WeightControl.AddService:output_type -> control.Empty
	4, // 9: control.WeightControl.DeleteService:output_type -> control.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_control_proto_init() }
func file_proto_control_proto_init() {
	if File_proto_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_control_proto_rawDesc), len(file_proto_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_control_proto_goTypes,
		DependencyIndexes: file_proto_control_proto_depIdxs,
		MessageInfos:      file_proto_control_proto_msgTypes,
	}.Build()
	File_proto_control_proto = out.File
	file_proto_control_proto_goTypes = nil
	file_proto_control_proto_depIdxs = nil
}
