// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type lb3Backend struct {
	_      structs.HostLayout
	Ip     uint32
	Port   uint16
	_      [2]byte
	Conns  uint32
	Weight uint16
	_      [2]byte
}

type lb3ConnMeta struct {
	_           structs.HostLayout
	Ip          uint32
	BackendIdx  uint32
	BackendPort uint16
	State       uint8
	_           [1]byte
}

type lb3FiveTupleT struct {
	_        structs.HostLayout
	SrcIp    uint32
	DstIp    uint32
	SrcPort  uint16
	DstPort  uint16
	Protocol uint8
	_        [3]byte
}

// loadLb3 returns the embedded CollectionSpec for lb3.
func loadLb3() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Lb3Bytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load lb3: %w", err)
	}

	return spec, err
}

// loadLb3Objects loads lb3 and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*lb3Objects
//	*lb3Programs
//	*lb3Maps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLb3Objects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLb3()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// lb3Specs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb3Specs struct {
	lb3ProgramSpecs
	lb3MapSpecs
	lb3VariableSpecs
}

// lb3ProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb3ProgramSpecs struct {
	XdpLoadBalancer *ebpf.ProgramSpec `ebpf:"xdp_load_balancer"`
}

// lb3MapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb3MapSpecs struct {
	BackendCount *ebpf.MapSpec `ebpf:"backend_count"`
	Backends     *ebpf.MapSpec `ebpf:"backends"`
	Backendtrack *ebpf.MapSpec `ebpf:"backendtrack"`
	Conntrack    *ebpf.MapSpec `ebpf:"conntrack"`
}

// lb3VariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type lb3VariableSpecs struct {
}

// lb3Objects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLb3Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb3Objects struct {
	lb3Programs
	lb3Maps
	lb3Variables
}

func (o *lb3Objects) Close() error {
	return _Lb3Close(
		&o.lb3Programs,
		&o.lb3Maps,
	)
}

// lb3Maps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLb3Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb3Maps struct {
	BackendCount *ebpf.Map `ebpf:"backend_count"`
	Backends     *ebpf.Map `ebpf:"backends"`
	Backendtrack *ebpf.Map `ebpf:"backendtrack"`
	Conntrack    *ebpf.Map `ebpf:"conntrack"`
}

func (m *lb3Maps) Close() error {
	return _Lb3Close(
		m.BackendCount,
		m.Backends,
		m.Backendtrack,
		m.Conntrack,
	)
}

// lb3Variables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLb3Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb3Variables struct {
}

// lb3Programs contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLb3Objects or ebpf.CollectionSpec.LoadAndAssign.
type lb3Programs struct {
	XdpLoadBalancer *ebpf.Program `ebpf:"xdp_load_balancer"`
}

func (p *lb3Programs) Close() error {
	return _Lb3Close(
		p.XdpLoadBalancer,
	)
}

func _Lb3Close(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed lb3_bpf.o
var _Lb3Bytes []byte
